AllCops:
  UseCache: true
  DisabledByDefault: false
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'surf.gemspec'

Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/BlockLength:
  Enabled: false
